name: LINE Notify
description: LINE Notify for GitHub Actions (deprecated)
inputs:
  channel_access_token:
    description: LINE Channel Access Token
    required: true
  message:
    description: Message
    required: true
runs:
  using: node20
  main: index.js
branding:
  icon: message-circle
  color: green
