name: LINE Broadcast Message Example
on:
  push:
    branches:
      - 'example'
jobs:
  broadcast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: LINE Broadcast Message
        uses: NickCity/line-broadcast-message@v1.0.0
        with:
          channel_access_token: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          message: "some message"
